services:
  migrate:
    build:
      context: .
      dockerfile: dockerfile
    image: migrate-plex-to-jellyfin:local
    volumes:
      - ./config.yml:/app/config.yml:ro
    entrypoint: ["python3", "migrate.py", "--config", "/app/config.yml"]
    restart: "no"
