services:
  migrate:
    container_name: migrate-plex-to-jellyfin
    # To build locally instead, use: build: .
    image: ghcr.io/drmxrcy/migrate-plex-to-jellyfin:latest
    user: "1000:1000"
    hostname: migrate-plex-to-jellyfin
    networks:
      - saltbox
    labels:
      com.github.saltbox.saltbox_managed: true
    volumes:
      - /opt/migrate-plex-to-jellyfin:/app/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt
    entrypoint: ["python3", "migrate.py", "--config", "/app/config/config.yml"]
    restart: "no"

networks:
  saltbox:
    external: true
